global:
  resolve_timeout: 5m

route:
  receiver: 'slack-notifications'

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - api_url: Place your webhho here
        channel: '#Sri Adithya Sridhar'  # optional, override default channel
        send_resolved: true
